on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Build Mosaic

jobs:
  build_macos:
    name: Build - macOS (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: Apple Silicon - Clang
            compiler: clang
          - os: macos-latest
            name: Apple Silicon - GCC
            compiler: gcc-14
          - os: macos-13
            name: Intel - Clang
            compiler: clang
          - os: macos-13
            name: Intel - GCC
            compiler: gcc-14

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install libpng openmotif xquartz

      - name: Build Mosaic - macOS
        run: |
          make osx CC=${{ matrix.compiler }}

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-${{ matrix.name }}-${{ matrix.compiler }}
          path: mosaic-build/mosaic

  build_linux:
    name: Build - Linux (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: OL8 - GCC - x86_64
            compiler: gcc
            arch: x86_64
          - name: OL8 - Clang - x86_64
            compiler: clang
            arch: x86_64
          - name: OL8 - GCC - aarch64
            compiler: gcc
            arch: aarch64
          - name: OL8 - clang - aarch64
            compiler: clang
            arch: aarch64
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.name }}-${{ matrix.compiler }}}-${{ matrix.arch }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build Mosaic - Linux
        run: |
          docker run -t \
          --rm \
          --platform linux/${{ matrix.arch }} \
          -v $PWD:/share \
          -e CC=${{ matrix.compiler }} \
          oraclelinux:8 \
          /share/.github/workflows/scripts/build-linux.sh

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-${{ matrix.name }}-${{ matrix.arch }}-${{ matrix.compiler }}
          path: mosaic-build/mosaic
