on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Build Mosaic

jobs:
  build_macos:
    name: Build - macOS
    runs-on: macos-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install libpng openmotif xquartz

      - name: Build Mosaic - macOS
        run: |
          make osx
