on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Build Mosaic

jobs:
  build_macos:
    name: Build - macOS (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        - os: macos-latest
          name: Apple Silicon
        - os: macos-13
          name: Intel
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install libpng openmotif xquartz

      - name: Build Mosaic - macOS
        run: |
          make osx

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: mosaic-${{ matrix.name }}
          path: mosaic-build/mosaic
